urls.py
from django.urls import path, include
from django.contrib import admin

from books.views import*

app_name = 'opexa_books'

urlpatterns = [

    #Authentication Views
    path('login/', LoginView.as_view(),
        name = 'login'),
    path('new_account/login/<pk>/', AccountLoginShortCutView.as_view(),
        name = 'new_account_login'),

    # Account initialization views
    path('initialize_integrated_package/', InitializeIntegratedAccountView.as_view(),
        name = 'initialize_integrated_package'),
    path('new_account/', AccountRegistrationView.as_view(),
        name = 'new_account'),
    path('account_start/capital_sources/', CapitalSourcesView.as_view(),
        name = 'capital_sources'),
    path('account_start/liability_sources/', LiabilitySourcesView.as_view(),
        name = 'liability_sources'),
    path('account_start/asset_sources/', AssetsSourcesView.as_view(),
        name = 'asset_sources'),
    path('account_start/end/', end_declarations_view,
        name = 'end_declarations'),


    # Books Accounting Dashboard #
    ##############################
    path('', DashboardView.as_view(),
        name = 'home'),
    path('download_trial_balance/', DownloadTrialBalanceView.as_view(),
        name = 'download_trial_balance'),
    path('download_profit_and_loss/', DownloadProfitAndLossView.as_view(),
        name = 'download_profit_and_loss'),
    path('download_balance_sheet/', DownloadBalanceSheetView.as_view(),
        name = 'download_balance_sheet')

    
    
    
]

templates/books/dashboard/home.html
{% extends 'books/books_admin_base.html' %}
{% load static crispy_forms_tags %}

{% block page-content %}
<div class = 'row'>
<h1>Dashboard</h1>
</div> 
<div class = 'row'>
<div style="display: block">
    <p>Latest Financial Statements</p>
    <a class = 'btn btn-primary' href="{% url 'opexa_books:download_trial_balance' %}" target="_blank">Trial Balance</a>
    <a class = 'btn btn-primary' href="{% url 'opexa_books:download_profit_and_loss' %}" target="_blank">Profit and Loss</a>
    <a class = 'btn btn-primary' href="{% url 'opexa_books:download_balance_sheet' %}" target="_blank">Balance Sheet</a>
</div>
</div> 
{% endblock %}

templates/books/dashboard/initialize_integrated_acc.html
{% extends 'books/books_admin_base.html' %}
{% load crispy_forms_tags %}

{% block page-content %}
<p>You are about to initialize the accounting books for <strong>{{username}}</strong>. Are you sure you would like to contimue?</p>
{% crispy form %}
{% endblock %}